### ISSUE TITLE
Error while running Train model

### ISSUE THREAD

**Issue by linhduongtuan** [yashbhalgat/MRNet-Competition#1]
Dear Bhalgat
first of all, I thank for your very nice code. However, I try to run yours and raise an error like:
ValueError                                Traceback (most recent call last)
<ipython-input-42-b5234b2ca292> in <module>()
    103   json.dump(vars(args), out, indent=4)
    104 
--> 105 train(args.rundir, args.task, args.backbone, args.epochs, args.learning_rate, args.gpu, abnormal_model_path=args.abnormal_model)

<ipython-input-42-b5234b2ca292> in train(rundir, task, backbone, epochs, learning_rate, use_gpu, abnormal_model_path)
     22             if fname.endswith(".json"):
     23                 continue
---> 24             ep = int(fname[27:])
     25             if ep >= max_epoch:
     26                 max_epoch = ep

ValueError: invalid literal for int() with base 10: 

==> Could you explain to me and fix an error?
Best wishes.
Linh

**Comment by felixk** [comment]
Create an empty directory and specify the rundir to be that empty directory.

**Comment by yashbhalgat** [comment]
Resolved.
