### ISSUE TITLE
Any clue on dataset avaiblity

### ISSUE THREAD

**Issue by gurkirt** [yashbhalgat/MRNet-Competition#3]
Hello, 

I am trying to use your network.

I downloaded the zip following the link from subscription email received after
registration at https://stanfordmlgroup.github.io/competitions/mrnet/.

However, I am not able to uncompress the files, I tried on 3 different
machines. I get the error saying unable to extract MRNet-v1.0.zip,
MRNet-v1.0.zip is an empty archive. Is it an ubuntu problem or data file problem?

Has anybody else reported the same problem? Do you have any solution to it?

Thanks
Gurkirt

**Comment by mohamedScikitLearn** [comment]
Hello Gurkit, 
I'm not sure if you are still looking for an answer, but it might be useful for others as well :) 
Here is a code tutorial by @ahmedbesbes, that shows how to do so 👍 
https://github.com/ahmedbesbes/mrnet

**Comment by gurkirt** [comment]
Thanks, @mohamedScikitLearn, yes, it might be useful for others. I am no longer interested in this problem.
